version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - .docker/database:/var/lib/mysql