version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    volumes:
      - ./web:/var/www/dev.lairdubois.fr/web
    ports:
      - 80:80
    links:
      - app

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    working_dir: /var/www/dev.lairdubois.fr
    volumes:
      - ./:/var/www/dev.lairdubois.fr

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - .docker/database:/var/lib/mysql

  elastic:
    image: elasticsearch:5.6
    environment:
      - discovery.type=single-node

  queue:
    image: rabbitmq

  memcached:
    image: memcached

  mail:
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25