<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160525235402 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE tbl_knowledge2_provider (id INT AUTO_INCREMENT NOT NULL, main_picture_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, contributor_count INT NOT NULL, positive_vote_count INT NOT NULL, negative_vote_count INT NOT NULL, vote_count INT NOT NULL, like_count INT NOT NULL, watch_count INT NOT NULL, comment_count INT NOT NULL, view_count INT NOT NULL, brand VARCHAR(100) DEFAULT NULL, store VARCHAR(100) DEFAULT NULL, sign VARCHAR(255) DEFAULT NULL, signRejected TINYINT(1) NOT NULL, website VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, geographicalAreas LONGTEXT DEFAULT NULL, postalCode VARCHAR(20) DEFAULT NULL, locality VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, inStoreSelling TINYINT(1) DEFAULT NULL, mailOrderSelling TINYINT(1) DEFAULT NULL, saleToIndividuals TINYINT(1) DEFAULT NULL, products LONGTEXT DEFAULT NULL, services LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, changed_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_draft TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_C77BF61E989D9B62 (slug), INDEX IDX_C77BF61ED6BDC9DC (main_picture_id), INDEX IDX_C77BF61E7E9E4C8C (photo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_sign (provider_id INT NOT NULL, sign_id INT NOT NULL, INDEX IDX_B69D3A6AA53A8AA (provider_id), INDEX IDX_B69D3A6A6FC7C15 (sign_id), PRIMARY KEY(provider_id, sign_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_logo (provider_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_CD6D3187A53A8AA (provider_id), INDEX IDX_CD6D3187EE45BDBF (picture_id), PRIMARY KEY(provider_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_photo (provider_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_E3FC30EEA53A8AA (provider_id), INDEX IDX_E3FC30EEEE45BDBF (picture_id), PRIMARY KEY(provider_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_website (provider_id INT NOT NULL, url_id INT NOT NULL, INDEX IDX_C9859B02A53A8AA (provider_id), INDEX IDX_C9859B0281CFDAE7 (url_id), PRIMARY KEY(provider_id, url_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_address (provider_id INT NOT NULL, location_id INT NOT NULL, INDEX IDX_83A4A964A53A8AA (provider_id), INDEX IDX_83A4A96464D218E (location_id), PRIMARY KEY(provider_id, location_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_phone (provider_id INT NOT NULL, phone_id INT NOT NULL, INDEX IDX_B304232BA53A8AA (provider_id), INDEX IDX_B304232B3B7323CB (phone_id), PRIMARY KEY(provider_id, phone_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_in_store_selling (provider_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_D56490DAA53A8AA (provider_id), INDEX IDX_D56490DAB7585238 (integer_id), PRIMARY KEY(provider_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_mail_order_selling (provider_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_7C7B5D72A53A8AA (provider_id), INDEX IDX_7C7B5D72B7585238 (integer_id), PRIMARY KEY(provider_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_sale_to_individuals (provider_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_6F2921AA53A8AA (provider_id), INDEX IDX_6F2921AB7585238 (integer_id), PRIMARY KEY(provider_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_products (provider_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_6354A66BA53A8AA (provider_id), INDEX IDX_6354A66B698D3548 (text_id), PRIMARY KEY(provider_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_provider_value_services (provider_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_A3DC1D58A53A8AA (provider_id), INDEX IDX_A3DC1D58698D3548 (text_id), PRIMARY KEY(provider_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, parent_entity_type SMALLINT NOT NULL, parent_entity_id INT NOT NULL, parent_entity_field VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, legend VARCHAR(255) DEFAULT NULL, source_type SMALLINT DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, positive_vote_score INT NOT NULL, negative_vote_score INT NOT NULL, vote_score INT NOT NULL, vote_count INT NOT NULL, data_hash VARCHAR(32) NOT NULL, comment_count INT NOT NULL, discr INT NOT NULL, INDEX IDX_5AD32FB3A76ED395 (user_id), UNIQUE INDEX data_unique (data_hash, parent_entity_type, parent_entity_id, parent_entity_field), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_integer (id INT NOT NULL, data INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_location (id INT NOT NULL, data VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, postalCode VARCHAR(255) DEFAULT NULL, locality VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, geographicalAreas VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_phone (id INT NOT NULL, data VARCHAR(20) NOT NULL, rawPhoneNumber VARCHAR(20) NOT NULL, country VARCHAR(2) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_picture (id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_E5168F2EEE45BDBF (picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_sign (id INT NOT NULL, data VARCHAR(100) NOT NULL, brand VARCHAR(100) NOT NULL, store VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_text (id INT NOT NULL, data VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_value_url (id INT NOT NULL, data VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_texture (id INT AUTO_INCREMENT NOT NULL, wood_id INT NOT NULL, value_id INT NOT NULL, single_picture_id INT NOT NULL, mosaic_picture_id INT NOT NULL, download_count INT NOT NULL, INDEX IDX_82B6C00E7B2710BE (wood_id), INDEX IDX_82B6C00EF920BBA2 (value_id), INDEX IDX_82B6C00E9E971BFA (single_picture_id), INDEX IDX_82B6C00E29CFA3F3 (mosaic_picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood (id INT AUTO_INCREMENT NOT NULL, main_picture_id INT DEFAULT NULL, endgrain_id INT DEFAULT NULL, lumber_id INT DEFAULT NULL, tree_id INT DEFAULT NULL, leaf_id INT DEFAULT NULL, bark_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, contributor_count INT NOT NULL, positive_vote_count INT NOT NULL, negative_vote_count INT NOT NULL, vote_count INT NOT NULL, like_count INT NOT NULL, watch_count INT NOT NULL, comment_count INT NOT NULL, view_count INT NOT NULL, name LONGTEXT DEFAULT NULL, nameRejected TINYINT(1) NOT NULL, scientificname LONGTEXT DEFAULT NULL, englishname LONGTEXT DEFAULT NULL, family INT DEFAULT NULL, density INT DEFAULT NULL, availability INT DEFAULT NULL, price INT DEFAULT NULL, origin LONGTEXT DEFAULT NULL, utilization LONGTEXT DEFAULT NULL, texture_count INT NOT NULL, created_at DATETIME NOT NULL, changed_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_draft TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_2A25E1E3989D9B62 (slug), INDEX IDX_2A25E1E3D6BDC9DC (main_picture_id), INDEX IDX_2A25E1E3300F528C (endgrain_id), INDEX IDX_2A25E1E31E57F696 (lumber_id), INDEX IDX_2A25E1E378B64A2 (tree_id), INDEX IDX_2A25E1E3AA5C8D06 (leaf_id), INDEX IDX_2A25E1E3B4D881C2 (bark_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_name (wood_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_52A0CF3C7B2710BE (wood_id), INDEX IDX_52A0CF3C698D3548 (text_id), PRIMARY KEY(wood_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_scientificname (wood_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_91838D087B2710BE (wood_id), INDEX IDX_91838D08698D3548 (text_id), PRIMARY KEY(wood_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_englishname (wood_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_1EC442357B2710BE (wood_id), INDEX IDX_1EC44235698D3548 (text_id), PRIMARY KEY(wood_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_grain (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_BD2653F27B2710BE (wood_id), INDEX IDX_BD2653F2EE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_endgrain (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_4AD3FEEF7B2710BE (wood_id), INDEX IDX_4AD3FEEFEE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_lumber (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_4297EFBF7B2710BE (wood_id), INDEX IDX_4297EFBFEE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_tree (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_BBBDEFE67B2710BE (wood_id), INDEX IDX_BBBDEFE6EE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_leaf (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_CA1CB1DD7B2710BE (wood_id), INDEX IDX_CA1CB1DDEE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_bark (wood_id INT NOT NULL, picture_id INT NOT NULL, INDEX IDX_3294531D7B2710BE (wood_id), INDEX IDX_3294531DEE45BDBF (picture_id), PRIMARY KEY(wood_id, picture_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_family (wood_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_3C2970BB7B2710BE (wood_id), INDEX IDX_3C2970BBB7585238 (integer_id), PRIMARY KEY(wood_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_density (wood_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_603B47D37B2710BE (wood_id), INDEX IDX_603B47D3B7585238 (integer_id), PRIMARY KEY(wood_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_availability (wood_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_F06C22697B2710BE (wood_id), INDEX IDX_F06C2269B7585238 (integer_id), PRIMARY KEY(wood_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_price (wood_id INT NOT NULL, integer_id INT NOT NULL, INDEX IDX_CC878DA7B2710BE (wood_id), INDEX IDX_CC878DAB7585238 (integer_id), PRIMARY KEY(wood_id, integer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_origin (wood_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_473E07FE7B2710BE (wood_id), INDEX IDX_473E07FE698D3548 (text_id), PRIMARY KEY(wood_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tbl_knowledge2_wood_value_utilization (wood_id INT NOT NULL, text_id INT NOT NULL, INDEX IDX_F63022BD7B2710BE (wood_id), INDEX IDX_F63022BD698D3548 (text_id), PRIMARY KEY(wood_id, text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider ADD CONSTRAINT FK_C77BF61ED6BDC9DC FOREIGN KEY (main_picture_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider ADD CONSTRAINT FK_C77BF61E7E9E4C8C FOREIGN KEY (photo_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sign ADD CONSTRAINT FK_B69D3A6AA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sign ADD CONSTRAINT FK_B69D3A6A6FC7C15 FOREIGN KEY (sign_id) REFERENCES tbl_knowledge2_value_sign (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_logo ADD CONSTRAINT FK_CD6D3187A53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_logo ADD CONSTRAINT FK_CD6D3187EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_photo ADD CONSTRAINT FK_E3FC30EEA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_photo ADD CONSTRAINT FK_E3FC30EEEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_website ADD CONSTRAINT FK_C9859B02A53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_website ADD CONSTRAINT FK_C9859B0281CFDAE7 FOREIGN KEY (url_id) REFERENCES tbl_knowledge2_value_url (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_address ADD CONSTRAINT FK_83A4A964A53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_address ADD CONSTRAINT FK_83A4A96464D218E FOREIGN KEY (location_id) REFERENCES tbl_knowledge2_value_location (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_phone ADD CONSTRAINT FK_B304232BA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_phone ADD CONSTRAINT FK_B304232B3B7323CB FOREIGN KEY (phone_id) REFERENCES tbl_knowledge2_value_phone (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_in_store_selling ADD CONSTRAINT FK_D56490DAA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_in_store_selling ADD CONSTRAINT FK_D56490DAB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_mail_order_selling ADD CONSTRAINT FK_7C7B5D72A53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_mail_order_selling ADD CONSTRAINT FK_7C7B5D72B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sale_to_individuals ADD CONSTRAINT FK_6F2921AA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sale_to_individuals ADD CONSTRAINT FK_6F2921AB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_products ADD CONSTRAINT FK_6354A66BA53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_products ADD CONSTRAINT FK_6354A66B698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_services ADD CONSTRAINT FK_A3DC1D58A53A8AA FOREIGN KEY (provider_id) REFERENCES tbl_knowledge2_provider (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_services ADD CONSTRAINT FK_A3DC1D58698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value ADD CONSTRAINT FK_5AD32FB3A76ED395 FOREIGN KEY (user_id) REFERENCES tbl_core_user (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_integer ADD CONSTRAINT FK_A9C26BACBF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_location ADD CONSTRAINT FK_16DF7240BF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_phone ADD CONSTRAINT FK_44721F5EBF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_picture ADD CONSTRAINT FK_E5168F2EEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_picture ADD CONSTRAINT FK_E5168F2EBF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_sign ADD CONSTRAINT FK_A2F612FEBF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_text ADD CONSTRAINT FK_60324C7BF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_url ADD CONSTRAINT FK_A46092CBBF396750 FOREIGN KEY (id) REFERENCES tbl_knowledge2_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture ADD CONSTRAINT FK_82B6C00E7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture ADD CONSTRAINT FK_82B6C00EF920BBA2 FOREIGN KEY (value_id) REFERENCES tbl_knowledge2_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture ADD CONSTRAINT FK_82B6C00E9E971BFA FOREIGN KEY (single_picture_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture ADD CONSTRAINT FK_82B6C00E29CFA3F3 FOREIGN KEY (mosaic_picture_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E3D6BDC9DC FOREIGN KEY (main_picture_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E3300F528C FOREIGN KEY (endgrain_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E31E57F696 FOREIGN KEY (lumber_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E378B64A2 FOREIGN KEY (tree_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E3AA5C8D06 FOREIGN KEY (leaf_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood ADD CONSTRAINT FK_2A25E1E3B4D881C2 FOREIGN KEY (bark_id) REFERENCES tbl_core_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_name ADD CONSTRAINT FK_52A0CF3C7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_name ADD CONSTRAINT FK_52A0CF3C698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_scientificname ADD CONSTRAINT FK_91838D087B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_scientificname ADD CONSTRAINT FK_91838D08698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_englishname ADD CONSTRAINT FK_1EC442357B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_englishname ADD CONSTRAINT FK_1EC44235698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_grain ADD CONSTRAINT FK_BD2653F27B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_grain ADD CONSTRAINT FK_BD2653F2EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_endgrain ADD CONSTRAINT FK_4AD3FEEF7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_endgrain ADD CONSTRAINT FK_4AD3FEEFEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_lumber ADD CONSTRAINT FK_4297EFBF7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_lumber ADD CONSTRAINT FK_4297EFBFEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_tree ADD CONSTRAINT FK_BBBDEFE67B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_tree ADD CONSTRAINT FK_BBBDEFE6EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_leaf ADD CONSTRAINT FK_CA1CB1DD7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_leaf ADD CONSTRAINT FK_CA1CB1DDEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_bark ADD CONSTRAINT FK_3294531D7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_bark ADD CONSTRAINT FK_3294531DEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge2_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_family ADD CONSTRAINT FK_3C2970BB7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_family ADD CONSTRAINT FK_3C2970BBB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_density ADD CONSTRAINT FK_603B47D37B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_density ADD CONSTRAINT FK_603B47D3B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_availability ADD CONSTRAINT FK_F06C22697B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_availability ADD CONSTRAINT FK_F06C2269B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_price ADD CONSTRAINT FK_CC878DA7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_price ADD CONSTRAINT FK_CC878DAB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge2_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_origin ADD CONSTRAINT FK_473E07FE7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_origin ADD CONSTRAINT FK_473E07FE698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_utilization ADD CONSTRAINT FK_F63022BD7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge2_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_utilization ADD CONSTRAINT FK_F63022BD698D3548 FOREIGN KEY (text_id) REFERENCES tbl_knowledge2_value_text (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_value_integer_vote DROP FOREIGN KEY FK_4A2695DAB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_value_integer_vote ADD CONSTRAINT FK_4A2695DAB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_value_picture_vote DROP FOREIGN KEY FK_E513DA2EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_value_picture_vote ADD CONSTRAINT FK_E513DA2EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_value_string_vote DROP FOREIGN KEY FK_427096C24AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_value_string_vote ADD CONSTRAINT FK_427096C24AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood CHANGE slug slug VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name DROP FOREIGN KEY FK_847A7B2E4AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name DROP FOREIGN KEY FK_847A7B2E7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name ADD CONSTRAINT FK_847A7B2E4AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name ADD CONSTRAINT FK_847A7B2E7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname DROP FOREIGN KEY FK_F89E11E74AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname DROP FOREIGN KEY FK_F89E11E77B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname ADD CONSTRAINT FK_F89E11E74AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname ADD CONSTRAINT FK_F89E11E77B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname DROP FOREIGN KEY FK_AFA41F0C4AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname DROP FOREIGN KEY FK_AFA41F0C7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname ADD CONSTRAINT FK_AFA41F0C4AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname ADD CONSTRAINT FK_AFA41F0C7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain DROP FOREIGN KEY FK_DBF807E57B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain DROP FOREIGN KEY FK_DBF807E5EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain ADD CONSTRAINT FK_4E49F80E7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain ADD CONSTRAINT FK_4E49F80EEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain DROP FOREIGN KEY FK_66F36D437B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain DROP FOREIGN KEY FK_66F36D43EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain ADD CONSTRAINT FK_66F36D437B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain ADD CONSTRAINT FK_66F36D43EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber DROP FOREIGN KEY FK_F66F3E237B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber DROP FOREIGN KEY FK_F66F3E23EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber ADD CONSTRAINT FK_F66F3E237B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber ADD CONSTRAINT FK_F66F3E23EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree DROP FOREIGN KEY FK_6D675BF47B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree DROP FOREIGN KEY FK_6D675BF4EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree ADD CONSTRAINT FK_6D675BF47B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree ADD CONSTRAINT FK_6D675BF4EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf DROP FOREIGN KEY FK_1CC605CF7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf DROP FOREIGN KEY FK_1CC605CFEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf ADD CONSTRAINT FK_1CC605CF7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf ADD CONSTRAINT FK_1CC605CFEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark DROP FOREIGN KEY FK_E44EE70F7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark DROP FOREIGN KEY FK_E44EE70FEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark ADD CONSTRAINT FK_E44EE70F7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark ADD CONSTRAINT FK_E44EE70FEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family DROP FOREIGN KEY FK_88D1A1277B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family DROP FOREIGN KEY FK_88D1A127B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family ADD CONSTRAINT FK_88D1A1277B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family ADD CONSTRAINT FK_88D1A127B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density DROP FOREIGN KEY FK_9936606D7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density DROP FOREIGN KEY FK_9936606DB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density ADD CONSTRAINT FK_9936606D7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density ADD CONSTRAINT FK_9936606DB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability DROP FOREIGN KEY FK_AFD8CA3C7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability DROP FOREIGN KEY FK_AFD8CA3CB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability ADD CONSTRAINT FK_AFD8CA3C7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability ADD CONSTRAINT FK_AFD8CA3CB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price DROP FOREIGN KEY FK_FFA7D3267B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price DROP FOREIGN KEY FK_FFA7D326B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price ADD CONSTRAINT FK_FFA7D3267B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price ADD CONSTRAINT FK_FFA7D326B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin DROP FOREIGN KEY FK_F3C6D6624AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin DROP FOREIGN KEY FK_F3C6D6627B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin ADD CONSTRAINT FK_F3C6D6624AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin ADD CONSTRAINT FK_F3C6D6627B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization DROP FOREIGN KEY FK_47507F844AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization DROP FOREIGN KEY FK_47507F847B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization ADD CONSTRAINT FK_47507F844AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id)');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization ADD CONSTRAINT FK_47507F847B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id)');
        $this->addSql('ALTER TABLE tbl_core_user_meta ADD unlisted_provider_count INT NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sign DROP FOREIGN KEY FK_B69D3A6AA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_logo DROP FOREIGN KEY FK_CD6D3187A53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_photo DROP FOREIGN KEY FK_E3FC30EEA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_website DROP FOREIGN KEY FK_C9859B02A53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_address DROP FOREIGN KEY FK_83A4A964A53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_phone DROP FOREIGN KEY FK_B304232BA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_in_store_selling DROP FOREIGN KEY FK_D56490DAA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_mail_order_selling DROP FOREIGN KEY FK_7C7B5D72A53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sale_to_individuals DROP FOREIGN KEY FK_6F2921AA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_products DROP FOREIGN KEY FK_6354A66BA53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_services DROP FOREIGN KEY FK_A3DC1D58A53A8AA');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_integer DROP FOREIGN KEY FK_A9C26BACBF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_location DROP FOREIGN KEY FK_16DF7240BF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_phone DROP FOREIGN KEY FK_44721F5EBF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_picture DROP FOREIGN KEY FK_E5168F2EBF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_sign DROP FOREIGN KEY FK_A2F612FEBF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_text DROP FOREIGN KEY FK_60324C7BF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_value_url DROP FOREIGN KEY FK_A46092CBBF396750');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_in_store_selling DROP FOREIGN KEY FK_D56490DAB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_mail_order_selling DROP FOREIGN KEY FK_7C7B5D72B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sale_to_individuals DROP FOREIGN KEY FK_6F2921AB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_family DROP FOREIGN KEY FK_3C2970BBB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_density DROP FOREIGN KEY FK_603B47D3B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_availability DROP FOREIGN KEY FK_F06C2269B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_price DROP FOREIGN KEY FK_CC878DAB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_address DROP FOREIGN KEY FK_83A4A96464D218E');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_phone DROP FOREIGN KEY FK_B304232B3B7323CB');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_logo DROP FOREIGN KEY FK_CD6D3187EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_photo DROP FOREIGN KEY FK_E3FC30EEEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture DROP FOREIGN KEY FK_82B6C00EF920BBA2');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_grain DROP FOREIGN KEY FK_BD2653F2EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_endgrain DROP FOREIGN KEY FK_4AD3FEEFEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_lumber DROP FOREIGN KEY FK_4297EFBFEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_tree DROP FOREIGN KEY FK_BBBDEFE6EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_leaf DROP FOREIGN KEY FK_CA1CB1DDEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_bark DROP FOREIGN KEY FK_3294531DEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_sign DROP FOREIGN KEY FK_B69D3A6A6FC7C15');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_products DROP FOREIGN KEY FK_6354A66B698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_services DROP FOREIGN KEY FK_A3DC1D58698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_name DROP FOREIGN KEY FK_52A0CF3C698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_scientificname DROP FOREIGN KEY FK_91838D08698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_englishname DROP FOREIGN KEY FK_1EC44235698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_origin DROP FOREIGN KEY FK_473E07FE698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_utilization DROP FOREIGN KEY FK_F63022BD698D3548');
        $this->addSql('ALTER TABLE tbl_knowledge2_provider_value_website DROP FOREIGN KEY FK_C9859B0281CFDAE7');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_texture DROP FOREIGN KEY FK_82B6C00E7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_name DROP FOREIGN KEY FK_52A0CF3C7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_scientificname DROP FOREIGN KEY FK_91838D087B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_englishname DROP FOREIGN KEY FK_1EC442357B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_grain DROP FOREIGN KEY FK_BD2653F27B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_endgrain DROP FOREIGN KEY FK_4AD3FEEF7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_lumber DROP FOREIGN KEY FK_4297EFBF7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_tree DROP FOREIGN KEY FK_BBBDEFE67B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_leaf DROP FOREIGN KEY FK_CA1CB1DD7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_bark DROP FOREIGN KEY FK_3294531D7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_family DROP FOREIGN KEY FK_3C2970BB7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_density DROP FOREIGN KEY FK_603B47D37B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_availability DROP FOREIGN KEY FK_F06C22697B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_price DROP FOREIGN KEY FK_CC878DA7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_origin DROP FOREIGN KEY FK_473E07FE7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge2_wood_value_utilization DROP FOREIGN KEY FK_F63022BD7B2710BE');
        $this->addSql('DROP TABLE tbl_knowledge2_provider');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_sign');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_logo');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_photo');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_website');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_address');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_phone');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_in_store_selling');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_mail_order_selling');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_sale_to_individuals');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_products');
        $this->addSql('DROP TABLE tbl_knowledge2_provider_value_services');
        $this->addSql('DROP TABLE tbl_knowledge2_value');
        $this->addSql('DROP TABLE tbl_knowledge2_value_integer');
        $this->addSql('DROP TABLE tbl_knowledge2_value_location');
        $this->addSql('DROP TABLE tbl_knowledge2_value_phone');
        $this->addSql('DROP TABLE tbl_knowledge2_value_picture');
        $this->addSql('DROP TABLE tbl_knowledge2_value_sign');
        $this->addSql('DROP TABLE tbl_knowledge2_value_text');
        $this->addSql('DROP TABLE tbl_knowledge2_value_url');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_texture');
        $this->addSql('DROP TABLE tbl_knowledge2_wood');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_name');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_scientificname');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_englishname');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_grain');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_endgrain');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_lumber');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_tree');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_leaf');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_bark');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_family');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_density');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_availability');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_price');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_origin');
        $this->addSql('DROP TABLE tbl_knowledge2_wood_value_utilization');
        $this->addSql('ALTER TABLE tbl_core_user_meta DROP unlisted_provider_count');
        $this->addSql('ALTER TABLE tbl_knowledge_value_integer_vote DROP FOREIGN KEY FK_4A2695DAB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_value_integer_vote ADD CONSTRAINT FK_4A2695DAB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_value_picture_vote DROP FOREIGN KEY FK_E513DA2EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_value_picture_vote ADD CONSTRAINT FK_E513DA2EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_value_string_vote DROP FOREIGN KEY FK_427096C24AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_value_string_vote ADD CONSTRAINT FK_427096C24AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood CHANGE slug slug VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability DROP FOREIGN KEY FK_AFD8CA3C7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability DROP FOREIGN KEY FK_AFD8CA3CB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability ADD CONSTRAINT FK_AFD8CA3C7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_availability ADD CONSTRAINT FK_AFD8CA3CB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark DROP FOREIGN KEY FK_E44EE70F7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark DROP FOREIGN KEY FK_E44EE70FEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark ADD CONSTRAINT FK_E44EE70F7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_bark ADD CONSTRAINT FK_E44EE70FEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density DROP FOREIGN KEY FK_9936606D7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density DROP FOREIGN KEY FK_9936606DB7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density ADD CONSTRAINT FK_9936606D7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_density ADD CONSTRAINT FK_9936606DB7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain DROP FOREIGN KEY FK_66F36D437B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain DROP FOREIGN KEY FK_66F36D43EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain ADD CONSTRAINT FK_66F36D437B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_endgrain ADD CONSTRAINT FK_66F36D43EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname DROP FOREIGN KEY FK_AFA41F0C7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname DROP FOREIGN KEY FK_AFA41F0C4AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname ADD CONSTRAINT FK_AFA41F0C7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_englishname ADD CONSTRAINT FK_AFA41F0C4AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family DROP FOREIGN KEY FK_88D1A1277B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family DROP FOREIGN KEY FK_88D1A127B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family ADD CONSTRAINT FK_88D1A1277B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_family ADD CONSTRAINT FK_88D1A127B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain DROP FOREIGN KEY FK_4E49F80E7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain DROP FOREIGN KEY FK_4E49F80EEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain ADD CONSTRAINT FK_DBF807E57B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_grain ADD CONSTRAINT FK_DBF807E5EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf DROP FOREIGN KEY FK_1CC605CF7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf DROP FOREIGN KEY FK_1CC605CFEE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf ADD CONSTRAINT FK_1CC605CF7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_leaf ADD CONSTRAINT FK_1CC605CFEE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber DROP FOREIGN KEY FK_F66F3E237B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber DROP FOREIGN KEY FK_F66F3E23EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber ADD CONSTRAINT FK_F66F3E237B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_lumber ADD CONSTRAINT FK_F66F3E23EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name DROP FOREIGN KEY FK_847A7B2E7B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name DROP FOREIGN KEY FK_847A7B2E4AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name ADD CONSTRAINT FK_847A7B2E7B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_name ADD CONSTRAINT FK_847A7B2E4AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin DROP FOREIGN KEY FK_F3C6D6627B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin DROP FOREIGN KEY FK_F3C6D6624AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin ADD CONSTRAINT FK_F3C6D6627B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_origin ADD CONSTRAINT FK_F3C6D6624AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price DROP FOREIGN KEY FK_FFA7D3267B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price DROP FOREIGN KEY FK_FFA7D326B7585238');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price ADD CONSTRAINT FK_FFA7D3267B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_price ADD CONSTRAINT FK_FFA7D326B7585238 FOREIGN KEY (integer_id) REFERENCES tbl_knowledge_value_integer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname DROP FOREIGN KEY FK_F89E11E77B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname DROP FOREIGN KEY FK_F89E11E74AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname ADD CONSTRAINT FK_F89E11E77B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_scientificname ADD CONSTRAINT FK_F89E11E74AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree DROP FOREIGN KEY FK_6D675BF47B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree DROP FOREIGN KEY FK_6D675BF4EE45BDBF');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree ADD CONSTRAINT FK_6D675BF47B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_tree ADD CONSTRAINT FK_6D675BF4EE45BDBF FOREIGN KEY (picture_id) REFERENCES tbl_knowledge_value_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization DROP FOREIGN KEY FK_47507F847B2710BE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization DROP FOREIGN KEY FK_47507F844AC2F1F0');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization ADD CONSTRAINT FK_47507F847B2710BE FOREIGN KEY (wood_id) REFERENCES tbl_knowledge_wood (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tbl_knowledge_wood_value_utilization ADD CONSTRAINT FK_47507F844AC2F1F0 FOREIGN KEY (string_id) REFERENCES tbl_knowledge_value_string (id) ON DELETE CASCADE');
    }
}
