FROM nginx

COPY /.docker/nginx/dev.lairdubois.fr.conf /etc/nginx/conf.d/dev.lairdubois.fr.conf
#COPY /.docker/server/nginx.conf /etc/nginx/nginx.conf

#RUN ln -s /etc/nginx/sites-available/dev.lairdubois.fr.conf /etc/nginx/sites-enabled/dev.lairdubois.fr.conf